<?php

declare(strict_types=1);

namespace Yangweijie\Ui2\Games\OnePieceDoudizhu;

use Yangweijie\Ui2\System\Audio;

/**
 * Sound-effects manager for the One Piece Doudizhu game.
 *
 * The nine WAV files are procedurally generated by scripts/gen-sfx.php into
 * assets/audio/. They are lazy-loaded and cached by name through the existing
 * miniaudio-backed Yangweijie\Ui2\System\Audio wrapper.
 *
 * Two ways to trigger a sound:
 *   - Sound::instance()->play(Sound::BOMB)        // explicit sound name
 *   - Sound::instance()->trigger('bomb')           // engine event name
 *
 * The event-name mapping (see DEFAULT_BINDINGS) lets the GUI/engine fire
 * named game events and have the right SFX play without knowing the file.
 */
final class Sound
{
    public const CLICK = 'click';
    public const DEAL = 'deal';
    public const PLAY = 'play';
    public const PASS = 'pass';
    public const BOMB = 'bomb';
    public const SKILL = 'skill';
    public const BID = 'bid';
    public const WIN = 'win';
    public const LOSE = 'lose';

    /** Maps a high-level game event to a sound name. */
    private const DEFAULT_BINDINGS = [
        'click' => self::CLICK,
        'deal' => self::DEAL,
        'play' => self::PLAY,
        'pass' => self::PASS,
        'bomb' => self::BOMB,
        'skill' => self::SKILL,
        'bid' => self::BID,
        'win' => self::WIN,
        'lose' => self::LOSE,
    ];

    private static ?self $instance = null;

    /** @var array<string, Audio> */
    private array $cache = [];
    /** @var array<string, string> */
    private array $bindings;
    private float $volume = 0.8;
    private bool $enabled = true;
    private string $dir;

    public function __construct(?string $dir = null)
    {
        $this->dir = $this->resolveDir($dir);
        $this->bindings = self::DEFAULT_BINDINGS;
    }

    public static function instance(?string $dir = null): self
    {
        return self::$instance ??= new self($dir);
    }

    /* ----------------------------- config ----------------------------- */

    public function setVolume(float $v): self
    {
        $this->volume = max(0.0, min(1.0, $v));
        return $this;
    }

    public function setEnabled(bool $on): self
    {
        $this->enabled = $on;
        return $this;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    /** Resolved directory the WAV files are loaded from (useful for the GUI). */
    public function directory(): string
    {
        return $this->dir;
    }

    /** Absolute path to a sound file if it exists, otherwise null. */
    public function pathFor(string $name): ?string
    {
        $path = $this->dir . '/' . $name . '.wav';
        return is_file($path) ? $path : null;
    }

    /** Override / extend the event -> sound mapping. */
    public function bind(string $event, string $sound): self
    {
        $this->bindings[$event] = $sound;
        return $this;
    }

    /* ----------------------------- trigger ---------------------------- */

    /** Play a sound by its file name (without .wav). */
    public function play(string $name): void
    {
        if (!$this->enabled) {
            return;
        }
        $audio = $this->load($name);
        if ($audio !== null) {
            $audio->setVolume($this->volume)->play();
        }
    }

    /** Fire a named game event; plays the bound sound if any. */
    public function trigger(string $event): void
    {
        $sound = $this->bindings[$event] ?? $event;
        $this->play($sound);
    }

    /* ----------------------------- loader ----------------------------- */

    private function load(string $name): ?Audio
    {
        if (isset($this->cache[$name])) {
            return $this->cache[$name];
        }
        $path = $this->dir . '/' . $name . '.wav';
        if (!file_exists($path)) {
            return null;
        }
        try {
            $audio = Audio::load($path);
        } catch (\Throwable) {
            return null;
        }
        return $this->cache[$name] = $audio;
    }

    public function unload(): void
    {
        foreach ($this->cache as $audio) {
            try {
                $audio->unload();
            } catch (\Throwable) {
                // already torn down
            }
        }
        $this->cache = [];
    }

    public function __destruct()
    {
        $this->unload();
    }

    /* ------------------------------ path ------------------------------ */

    private function resolveDir(?string $dir): string
    {
        if ($dir !== null) {
            return rtrim($dir, '/');
        }
        $candidates = [
            \dirname(__DIR__, 3) . '/assets/audio',
            (getcwd() ?: '') . '/assets/audio',
            __DIR__ . '/../../../assets/audio',
        ];
        foreach ($candidates as $c) {
            if ($c !== '' && is_dir($c)) {
                return rtrim($c, '/');
            }
        }
        return rtrim($candidates[0], '/');
    }
}
